# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_question_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted'),
        ),
    ]
